# Generated by Django 3.0.5 on 2020-08-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200405_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='detail_image',
            field=models.ImageField(null=True, upload_to='projects', verbose_name='Imagen en detalle'),
        ),
        migrations.AddField(
            model_name='project',
            name='list_image',
            field=models.ImageField(null=True, upload_to='projects', verbose_name='Imagen en lista'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Dirección web'),
        ),
    ]
