# Generated by Django 3.0.5 on 2020-08-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bg_image',
            field=models.ImageField(null=True, upload_to='projects', verbose_name='Imagen en fondo'),
        ),
    ]
